from sqlalchemy.orm import Session
from app import models
from app import schemas

def create_item(db: Session, item_data: schemas.ItemCreate):
    # Convert item_data that respects ItemCreate schema to database Item model
    db_item = models.Item(**item_data.model_dump())

    # Add it to session for writing to database
    db.add(db_item)

    # Commit (write) to database
    db.commit()

    # Refresh to retrieve autogenerated fields from the database
    db.refresh(db_item)

    # Return the saved item
    return db_item

def get_item(db: Session, querry_id: int):
    return db.query(models.Item).filter(models.Item.id == querry_id).first()

def get_items(db: Session):
    return db.query(models.Item).all()

def update_item(db: Session, querry_id: int, item_data: schemas.ItemUpdate):
    # Fetch the item with a querried id
    db_item = get_item(db, querry_id)

    # If it does not exist, return None
    if not db_item:
        return None
    
    # Take the updated information only
    update_data = item_data.model_dump(exclude_unset=True)

    # Update the fetched database item with the updated information
    for field, value in update_data.items():
        setattr(db_item, field, value)

    # Commit the changes to database
    db.commit()

    # Refresh the fetched database item to get updated timestamp 
    db.refresh(db_item)

    # Return the updated database item
    return db_item

def delete_item(db: Session, querry_id: int):
    # Fetch the item with a querried id
    db_item = get_item(db, querry_id)

    # If the item does not exist, return False
    if not db_item:
        return False

    # Delete the item from database
    db.delete(db_item)

    # Commit the change to database
    db.commit()

    # Return True upon successful deletion
    return True
